### ISSUE TITLE
cross graph events

### ISSUE THREAD

**Issue by peteasa** [AlgorithmHub/dash_building_blocks#2]
Using dash_building_blocks and found them very easy to use and a good way to manage larger designs.

Tried using them for hover and click type applications for example https://dash.plotly.com/interactive-graphing#update-graphs-on-hover

Because each of the classes has its own ids store when a link between two classes is needed, as in this example, the second class can not find the ids stored in the first class.
Is there an easy way to fix this, for example inherit from a common ids store?

<pre>class GraphPlot(dbb.Block):
    def layout(self):
       .... id = self.register('graph-plot'), ....
class XYZPlot(dbb.Block):
    def layout(self):
       .... id = self.register('xyz-plot'), ....
    def callbacks(self):
            @app.callback(
                self.output('xyz-plot', 'figure'),
                [self.input('graph-plot', 'hoverData')],
                [self.input('graph-plot', 'clickData')],
                [self.input('graph-plot, 'selectedData')],
                [self.state('graph-plot', 'figure')]
            )
</pre>

**Comment by peteasa** [comment]
I have just had a good look at this and found a possible solution.. Now that https://dash.plotly.com/dash-core-components/store is implemented I can simply use dash!
<code>    app = Dash(__name__, assets_folder='static')

    graphs = [ D1(1,2), D2(2,1) ]

    app.layout = html.Div([html.Div(graph.layout) for graph in graphs], className='container')
    for graph in graphs:
        graph.register_callback(app)

    app.run_server(debug=True, use_reloader=True)
</code>
in one file and in another
<code>class D1(object):

    def __init__(self, gid, rgid):
        self.gid = gid
        self.rgid = rgid

    @property
    def layout(self):
        return html.Div([
            html.Button('Click me', id="btn_{}".format(self.gid)),
            html.Div(id="output_{}".format(self.gid))
        ])

    def register_callback(self, app):
        @app.callback(Output("output_{}".format(self.rgid), 'children'), [Input("btn_{}".format(self.gid), 'n_clicks')])
        def on_click(n_clicks):
            return 'Clicked {} times'.format(n_clicks)
</code>
Then just include the various charts into the app file...

**Comment by marcodlk** [comment]
Hi @peteasa glad you're finding dash_building_blocks useful. Some context here: when we last updated this package, Dash did not yet have a native `Store` implementation, hence why we implemented our own version encapsulating how to achieve the "Store" functionality in practice at the time. Now that Dash has its own native `Store` that is definitely the way to go. Additionally, Dash has since added a lot of new features to support a more object-oriented approach natively, in particular [pattern-matching callbacks](https://dash.plotly.com/pattern-matching-callbacks) which allow you to implement [All-in-One components](https://dash.plotly.com/all-in-one-components).
